# Welcome to Jekyll!
#
# If you change something here, please rerun `jekyll serve`

# Site settings
title: SURGEON TUX
description: sudo rm -rf /* and we're done.
baseurl: "/surgeon-tux" # put subpath of your site, e.g. /blog
url: "http://lahiru.site" # put the base hostname & protocol for your site

email: lpsandaruwan@gmail.com
twitter_username: lpsandaruwan
github_username:  lpsandaruwan

paginate: 6

gems: [jekyll-paginate, kramdown]
markdown: kramdown
