# Welcome to Jekyll!
#
# If you change something here, please rerun `jekyll serve`

# Site settings
title: SURGEON TUX
email: lpsandaruwan@gmail.com
description: sudo rm -rf /* and we're done.
baseurl: "" # put subpath of your site, e.g. /blog
url: "" # put the base hostname & protocol for your site
twitter_username: lpsandaruwan
github_username:  lpsandaruwan
paginate: 6

gems: [jekyll-paginate, kramdown]
markdown: kramdown
